### ISSUE TITLE
周末活动：UserScript 用户脚本入门

### ISSUE THREAD

**Issue by kkocdko** [just-ca-unofficial/rfcs#1]
- 主题：UserScript 用户脚本入门。
- 时间：2022.11.26（周六）16:00 - 17:00。
- 地点：梦溪校区 教三 207。
- 参与限制：无 身份 / 水平限制。
- 主讲人：@kkocdko。

## 进度

- [x] 宣传文案与~~海报~~。
- [x] 讲解内容，大纲。
- [x] 反馈。

## 大纲

0. 环境准备，辨别常见浏览器 (Chromium / Firefox / Safari)，一些使用建议。
1. 引入浏览器扩展，安装脚本管理器。
2. 查找和推荐一些用户脚本。
3. 快速介绍 Web 基础技术。
4. 以 [古诗文网](https://www.gushiwen.cn) 为例，创建一个用户脚本，统计古诗字数。
5. 改造 [Bilibili 视频播放页](https://www.bilibili.com/video/BV1dW4y1W7kQ)，使热评显示到右侧。
6. 尝试特殊技巧：控制运行时机，选择器复杂组合，额外的 GM API，Hook 等。

**Comment by w-tianshui** [comment]
哈哈，有兴趣弄就好
要弄的话到时候我来凑个人头

还有一个小建议，就是有的话把涉及到的专业一点的名词在讲之前先简单罗列一下下
（小笨蛋真的会跟不上

**Comment by kkocdko** [comment]
反馈：好多人说 Web 基础那块讲得太快了，可是我觉得再慢也不可能压缩到一个小时内。。。
