### ISSUE TITLE
校赛题目选讲及常用容器科普

### ISSUE THREAD

**Issue by BaruchdeSpinoza** [just-ca-unofficial/rfcs#6]
- 主题：校赛题目选讲及常用容器科普
- 时间：2022.12.10（周六）15:00 - 17:00
- 地点：梦溪校区 教三 206。
- 参与限制：无 身份 / 水平限制。
- 主讲人：@BaruchdeSpinoza
### 大纲 ###

1. 校赛题目通过情况统计
2. 校赛中包含知识点讲解
3. 常用容器之vector
4. 常用容器之stack
5. 常用容器之queue
6. 常用容器之set
7. 常用容器之map

**Comment by kkocdko** [comment]
Finished.
